name = "subpool-worker"
main = "src/index.js"
compatibility_date = "2025-11-02"

workers_dev = true
# 关闭遥测
send_metrics = false

# KV 命名空间
[[kv_namespaces]]
binding = "KV"  # 不要修改此项
id = "e24c1a41ad47427688d307b9316eb7cb"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ADMIN_PASSWORD = "admin"
JWT_SECRET = "secret"